# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 11
  - name: Publications
    url: /#papers
    weight: 12
  - name: Talks
    url: /#talks
    weight: 17
  - name: Experience
    url: experience/
    weight: 16
  #- name: Projects
  #  url: projects/
  #  weight: 15
  - name: Awards
    url: /awards
    weight: 15
  #- name: Teaching
  #  url: teaching/
  #  weight: 30
  - name: Media
    url: /#media
    weight: 37
  - name: Teaching and Mentoring
    url: /#mentoring
    weight: 40
